###
* Template helpers for "materialize" template
###
Template['quickForm_materialize'].helpers
  submitButtonAtts: ->
    qfAtts = @atts
    atts = {}
    if typeof qfAtts.buttonClasses == 'string'
      atts['class'] = qfAtts.buttonClasses
    else
      atts['class'] = 'btn waves-effect waves-light'
    atts

Template['afFormGroup_materialize'].helpers
  skipLabel: ->
    self = this
    skipLabelTypes = [
      'checkbox'
      'checkbox-group'
      'boolean-checkbox'
      'select-radio'
      'select-radio-group'
      'select-radio-group-inline'
      'boolean-radio'
      'boolean-radio-group'
      'select'
      'boolean-select'
      'select-multiple'
      'toggle'
    ]
    type = AutoForm.getInputType(self.afFieldInputAtts)
    self.skipLabel or _.contains(skipLabelTypes, type)

  materializeFieldLabelAtts: ->
    atts = _.clone(@afFieldLabelAtts)
    atts

_.each [
  'afSelect_materialize'
  'afBooleanSelect_materialize'
  'afSelectMultiple_materialize'
  'afTextarea_materialize'
  'afInputText_materialize'
  'afInputPassword_materialize'
  'afInputDateTime_materialize'
  'afInputDateTimeLocal_materialize'
  'afInputDate_materialize'
  'afInputMonth_materialize'
  'afInputTime_materialize'
  'afInputWeek_materialize'
  'afInputNumber_materialize'
  'afInputEmail_materialize'
  'afInputUrl_materialize'
  'afInputSearch_materialize'
  'afInputTel_materialize'
  'afInputColor_materialize'
], (tmplName) ->
  Template[tmplName].helpers atts: ->
    atts = _.clone(@atts)
    atts
  return

_.each [
  'afInputButton_materialize'
  'afInputSubmit_materialize'
  'afInputReset_materialize'
], (tmplName) ->
  Template[tmplName].helpers atts: ->
    atts = _.clone(@atts)
    # Add bootstrap class
    atts = AutoForm.Utility.addClass(atts, 'button')
    atts
  return

Template['afRadio_materialize'].helpers atts: ->
  atts = _.clone(@atts)
  if @selected
    atts.checked = ''
  atts
_.each [
  'afCheckboxGroup_materialize'
  'afRadioGroup_materialize'
  'afCheckboxGroupInline_materialize'
  'afRadioGroupInline_materialize'
], (tmplName) ->
  Template[tmplName].helpers
    atts: ->
      atts = _.clone(@atts)
      if @selected
        atts.checked = ''
      # remove data-schema-key attribute because we put it
      # on the entire group
      delete atts['data-schema-key']
      console.log atts
      return atts
    dsk: ->
      { 'data-schema-key': @atts['data-schema-key'] }
  return

selectHelpers = optionAtts: ->
  item = this
  atts = value: item.value
  if item.selected
    atts.selected = ''
  atts

Template['afSelect_materialize'].helpers selectHelpers
Template['afSelectMultiple_materialize'].helpers selectHelpers
Template['afBooleanSelect_materialize'].helpers selectHelpers

Template['afBooleanRadioGroup_materialize'].helpers
  falseAtts: ->
    atts = _.omit(@atts, 'trueLabel', 'falseLabel', 'data-schema-key')
    if @value == false
      atts.checked = ''
    atts
  trueAtts: ->
    atts = _.omit(@atts, 'trueLabel', 'falseLabel', 'data-schema-key')
    if @value == true
      atts.checked = ''
    atts
  dsk: ->
    { 'data-schema-key': @atts['data-schema-key'] }

AutoForm.addInputType 'pickadate',
  template: 'afPickadate'
  valueIn: (val) ->
    formattedDate = moment(val).format "yyyy/mm/dd"
    return formattedDate
  valueOut: ->
    item = this.pickadate('picker').get('select')
    if item then result = item.obj
    result

Template.afFormGroup_materialize.rendered = ->
  template = this
  isFloating = template.$('.item-floating-label').length
  if isFloating
    template.$('input').on 'keyup.item-floating-label', (event) ->
      if $(this).val() != ''
        template.$('.item-floating-label .input-label').addClass 'has-input'
      else
        template.$('.item-floating-label .input-label').removeClass 'has-input'
      return
    template.$('input').trigger 'keydown.item-floating-label'
  return

Template.afFormGroup_materialize.destroyed = ->
  template = this
  template.$('input').off 'keyup.item-floating-label'
  return

Template['afPickadate'].rendered = ->
  @$('input')
    .pickadate(
      formatSubmit: 'yyyy/mm/dd',
      hiddenName: true
      closeOnSelect: true)
    .on('change', ->
      $(this).pickadate('picker').close()
    )

  if @data.value
    @$('input').parent().find('label').addClass 'active'
  return

# ---
# generated by js2coffee 2.0.1
